/*
 *  ======== config.h ========
 *  Configuration-specific definitions
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */
#ifndef config_h
#define config_h 1

#include "INA228.h"

/* support C++ sources */
#ifdef __cplusplus
extern "C" {
#endif

extern const INA228_Handle INA228;

#ifdef __cplusplus
}
#endif  /* C++ support end */

#endif  /* include guard */
